spring:
  application:
    name: gateway
  threads:
    virtual:
      enabled: true

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: scanner-management-service
              uri: lb://scanner-management-service
              predicates:
                - Path=/api/escaner/**
              filters:
                - AddRequestHeader=X-Gateway-Passed,true
            - id: marketdata-service
              uri: lb://marketdata-service
              predicates:
                - Path=/api/marketdata/**,/api/test/**
              filters:
                - AddRequestHeader=X-Gateway-Passed,true
            - id: asset-management-service
              uri: lb://asset-management-service
              predicates:
                - Path=/api/activos/**
              filters:
                - AddRequestHeader=X-Gateway-Passed,true
            - id: log-service
              uri: lb://log-service
              predicates:
                - Path=/api/logs/**
              filters:
                - AddRequestHeader=X-Gateway-Passed,true
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notificaciones/**
              filters:
                - AddRequestHeader=X-Gateway-Passed,true
                - AddResponseHeader=X-Accel-Buffering,no
                - AddResponseHeader=Cache-Control,no-cache
              metadata:
                response-timeout: -1
                connect-timeout: 10000
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

  profiles:
    active: prod

server:
  port: 8080
  netty:
    idle-timeout: 0

# Actuator for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
